/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizzbuzz.java.kotlin;

import org.junit.jupiter.api.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.greaterThan;


public class FizzBuzzJavaTest {
	@Test
	public void does_this_work() {
		assertThat(System.currentTimeMillis(), greaterThan(0L));
	}
}
